include: _default_template_yaml
task: simplevqa_en
process_docs: !function utils.process_en
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer the question directly and concisely."
