dataset_path: moonshotai/WorldVQA
dataset_kwargs:
  token: True
task: "worldvqa"
test_split: train
output_type: generate_until
doc_to_visual: !function utils.worldvqa_doc_to_visual
doc_to_text: !function utils.worldvqa_doc_to_text
doc_to_messages: !function utils.worldvqa_doc_to_messages
doc_to_target: "answer"

generation_kwargs:
  max_new_tokens: 256
  temperature: 0
  do_sample: false

process_results: !function utils.worldvqa_process_results

metric_list:
  - metric: worldvqa_accuracy
    aggregation: !function utils.worldvqa_aggregate_results
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""

metadata:
  - version: 0.0
