include: hrbench4k.yaml
task: hrbench4k_lookback
    
lmms_eval_specific_kwargs:
  default:
    system_prompt: ""
    pre_prompt: ""
    post_prompt: You FIRST think about the reasoning process as an internal monologue and then provide the final answer. The reasoning process MUST BE enclosed within <think> </think> tags, and use <back> </back> to verify your reasoning against the image. The final answer MUST BE put in \boxed{}, respectively, i.e., <think> reasoning process here </think> <back> verification process here </back> <think> continue reasoning </think> \boxed{final answer}.
