lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with the option letter only."
  qwen3_vl:
    pre_prompt: ""
    post_prompt: "Answer with the option letter only."
  vllm:
    pre_prompt: ""
    post_prompt: "Answer with the option letter only."
