lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with the option's letter from the given choices directly"
  qwen3_vl:
    pre_prompt: "Question: "
    post_prompt: "Answer with the option's letter from the given choices only."
  vllm:
    pre_prompt: "Question: "
    post_prompt: "Answer with the option's letter from the given choices only."