dataset_path: Lin-Chen/MMStar
task: "mmstar"
doc_to_visual: !function utils.mmstar_doc_to_visual
doc_to_text: !function utils.mmstar_doc_to_text
doc_to_messages: !function utils.mmstar_doc_to_messages
process_results: !function utils.mmstar_process_results
include: _default_template_yaml