include: _default_template_yaml
metric_list:
  - metric: vstar_overall_acc
    aggregation: !function utils.vstar_aggregate_results
    higher_is_better: true
  - metric: vstar_overall_llm_judge
    aggregation: !function utils.vstar_aggregate_results
    higher_is_better: true